### ISSUE TITLE
편집기 추가 기능(시간 되면 시도해볼 것)

### ISSUE THREAD

**Issue by mintnaka** [OASIS-YOP/23-2-YOP-Client#31]
## IssueName
> 시간되면 편집기에 추가할만한 기능

## Description
> 이슈에 대한 간단한 설명을 작성해주세요.

## Todo
- [ ] 오브젝트 이동시 가이드라인 기능
- [ ] 레이어 기능
- [ ] 스티커 추가
- [x] 스티커 리스트 카테고리 나눠서 따로 분류하기(탭으로 구분)
- [ ] 프레임 추가
- [ ] 오브젝트 그룹 기능
