### ISSUE TITLE
데모 이후 최종발표 이전 자잘한 이슈

### ISSUE THREAD

**Issue by sooje0ng** [OASIS-YOP/23-2-YOP-Client#67]
## IssueName
> 최종발표 이전 자잘한 이슈 해결

## Description
> 

## Todo
- [x] api 일괄 로그인모드로 고치기
- [x] 컬렉션페이지 - *****활성화안된아티스트 하얀색으로뜨는현상 코드 뜯어보기 ***********
- [x] 로그인 recoil로 전역변수관리
- [ ] 이미 activate된 collection은 collectionActive 막기
- [x] 커뮤니티페이지 - allpost 먼저 뜨게하기
- [x] artistpage(커뮤니티페이지)에서 다른 페이지 이동 시 에러나는 버그............get요청이 너무 많아서인가?
- [x] inputCodeModal에 있는 api요청코드 수정(하드코딩)
- [ ] 코드입력 활성화된컬렉션에 다시 예쁘게넣기
- [x] 내가가진 포카 수 하드코딩 고치기
- [x] 회원가입 성공 alert띄우기
- [x] 랜딩페이지 반응형(버튼 wrapper) -혜림님
- [x] 코드입력 버튼 zindex 조절.
