### ISSUE TITLE
개선 및 버그 수정

### ISSUE THREAD

**Issue by mintnaka** [OASIS-YOP/23-2-YOP-Client#69]
## IssueName
> 이슈 이름을 등록해주세요

## Description
> 이슈에 대한 간단한 설명을 작성해주세요.

## Todo
- [x] 도안 페이지 UI 수정하기
- [x] 컬렉션 탭에 있는 컬렉션 디테일 UI 손 보기
- [x] 포스팅 업로드 모달 구현해야함
- [x] 비어 있을 때 문구 수정(에디터 업로드 모달)
- [x] 활성화된 컬렉션에 코드 입력 가능하게 하기
- [x] 커뮤니티 페이지 아티스트 프로필 누를 시 해당 아티스트 도안 뜨는 거 안 됨
- [x] 커뮤니티 페이지 도안 페이지 진입해서 좋아요 눌러도 좋아요 안 올라감
